

services:
  # 1. Официальный векторный PostgreSQL с предустановленным расширением pgvector
  db:
    image: ankane/pgvector:latest
    container_name: smartcity_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    networks:
      - smartcity_network

  # 2. Наш Python бэкенд
  backend:
    build: .
    container_name: smartcity_backend
    restart: always
    volumes:
      - .:/app
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db  # Важно: внутри докер-сети хостом базы становится имя её сервиса
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - smartcity_network

volumes:
  pgvector_data:

networks:
  smartcity_network:
    driver: bridge